# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-15 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distances', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sector',
            unique_together=set([('x', 'y')]),
        ),
        migrations.AlterIndexTogether(
            name='sector',
            index_together=set([]),
        ),
    ]
